### ISSUE TITLE
URL to STASH is wrong

### ISSUE THREAD

**Issue by GerroDen** [jawspeak/intellij-plugin-copy-and-open-github-url#5]
Hi,

i like the plugin to share code points in issues.
But the URL given to our STASH is totally wrong.

Instead of the form:
`https://<host>/projects/<projectkey>/repos/<reponame>/browse/<filepath>#<line>`
I get something like:
`https://<host>/projects/7999/repos/<projectkey>/browse/<filepath>#<line>`
Is that an error in the plugin or did i misconfigure something? the git fetch, pull, etc. commands work alright.

**Comment by jawspeak** [comment]
What does your .git/config file look like?

On Wednesday, March 30, 2016, Lars-Erik Kimmel notifications@github.com
wrote:

> Hi,
> 
> i like the plugin to share code points in issues.
> But the URL given to our STASH is totally wrong.
> 
> Instead of the form:
> :///projects//repos//browse/#
> I get something like:
> :///projects/7999/repos//browse/#
> Is that an error in the plugin or did i misconfigure something? the git
> fetch, pull, etc. commands work alright.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> https://github.com/jawspeak/intellij-plugin-copy-and-open-github-url/issues/5

## 

Sent from my Phone

**Comment by GerroDen** [comment]
```
[core]
        repositoryformatversion = 0
        filemode = true
        bare = false
        logallrefupdates = true
[remote "origin"]
        url = ssh://git@<host>:<port>/<projectkey>/<reponame>.git
        fetch = +refs/heads/*:refs/remotes/origin/*
[branch "develop"]
        ...
[branch ...]
        ...
```

The port is for the remote to clone, checkout, etc. really is 7999, but out STASH is not reachable in the browser with that port.

Oh it killed my desciption from before -_- i fix my issue desciption.

This let's me guess, that the matching of port, projectkey and reponame are twisted.

BTW: we are running Atlassian Bitbucket Server v4.4.1 in our company. :) But it did not work in our STASH before the update with the renaming to Bitbucket Server either.

**Comment by jawspeak** [comment]
So probably you could make a very simple unit test and see the parsing
error. Otherwise thanks much - I will investigate later.

On Wednesday, March 30, 2016, Lars-Erik Kimmel notifications@github.com
wrote:

> [core]
>         repositoryformatversion = 0
>         filemode = true
>         bare = false
>         logallrefupdates = true
> [remote "origin"]
>         url = ssh://git@<host>:<port>/<projectkey>/<reponame>.git
>         fetch = +refs/heads/_:refs/remotes/origin/_
> [branch "develop"]
>         ...
> [branch ...]
>         ...
> 
> The port is for the remote to clone, checkout, etc. really is 7999, but
> out STASH is not reachable in the browser with that port.
> 
> Oh it killed my desciption from before -_- i fix my issue desciption.
> 
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> https://github.com/jawspeak/intellij-plugin-copy-and-open-github-url/issues/5#issuecomment-203498505

## 

Sent from my Phone

**Comment by fbradyirl** [comment]
Also seeing this problem. Is there a workaround?

**Comment by GerroDen** [comment]
PR is open :) https://github.com/jawspeak/intellij-plugin-copy-and-open-github-url/pull/6
